### ISSUE TITLE
Mark corebird as EOL

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.baedert.corebird#6]
Corebird is going to be discountinued, along with the twitter API it relies upon.

We'll need to add an EOL file to the repo, like this one for nautilus https://github.com/flathub/org.gnome.Nautilus/commit/691dce1d76b501fd35a42c9eeef30c351a742be3 and mark the repo as archived and read only.

Sad times.

**Comment by geekgonecrazy** [comment]
@nedrichards is this why posting tweets no longer works?  :(

Very sad indeed :(

**Comment by baedert** [comment]
No, that's probably because Corebird checks for network availability in the compose dialog and there's https://github.com/flatpak/xdg-desktop-portal/issues/208 now.
